### ISSUE TITLE
[BUG] new endpoints for integration environment

### ISSUE THREAD

**Issue by lme-atolcd** [InseeFr/Keycloak-FranceConnect#109]
**Describe the bug**
FranceConnect's integration environment seems to use new endpoints URL but only for newly created clients (old clients could still use the old endpoint).
* old endpoints : https://fcp.integ01.dev-franceconnect.fr/api/v1/ or https://auth.integ01.dev-franceconnect.fr/api/v2/
* new endpoint : https://fcp-low.integ01.dev-franceconnect.fr/api/v2/

See: https://docs.partenaires.franceconnect.gouv.fr/fd/technique/fd-technique-environnements/

**To Reproduce**
1. ask FranceConnect to create a new client
2. in Keycloak, create a new Identity provider "France Connect Particulier"
3. try to connect with the "France Connect Particulier" idp
    * with INTEGRATION_V1: "Erreur E000019"
    * with INTEGRATION_V2: "Erreur Y030106" "invalid_client"

But, now if I delete the "France Connect Particulier" idp and create a new "OpenID Connect v1.0" idp with the new endpoints (with the following discovery endpoint https://fcp-low.integ01.dev-franceconnect.fr/api/v2/.well-known/openid-configuration and appending "?acr_values=eidas1" to the authorization URL), I can log in with FC.

With previously created FC clients, I can still use INTEGRATION_V1.

**Additional context**
 - Keycloak Version 24.0.4
 - Extension Version 6.2.0

**Comment by clement-dufaure** [comment]
https://github.com/InseeFr/Keycloak-FranceConnect/pull/114

**Comment by clement-dufaure** [comment]
see https://github.com/InseeFr/Keycloak-FranceConnect/pull/114
