### ISSUE TITLE
Add mapper automatically at the provider creation

### ISSUE THREAD

**Issue by micedre** [InseeFr/Keycloak-FranceConnect#12]

**Comment by mboisnard** [comment]
Which mappers should we add automatically? (lastName, firstName and email, or more?)

**Comment by micedre** [comment]
at least those three. 
One idea was also to add all possible mappers, because it is a lot simpler to disable a mapper than add it. I am not sure about the best way. I think it is better for privacy to force adding mapper manually to avoid getting too much information (hello gdpr...), but I see how it is a pain to add all the mappers...
What do you think ? 
@ArnaultMICHEL @JulietteS , an idea ?

**Comment by mboisnard** [comment]
@micedre I think we can create a script to add the complete list of mappers using the REST Keycloak API (https://www.keycloak.org/docs-api/9.0/rest-api/index.html -> POST /{realm}/identity-provider/instances/{alias}/mappers) and try to create automatically lastName, firstName, and email mappers.
But I don't see anything to help us to save an `IdentityProviderMapperRepresentation` or an `IdentityProviderMapperModel` at IdentityProvider creation :/

**Comment by micedre** [comment]
I thought we could try something as keycloak does for ldap federation in https://github.com/keycloak/keycloak/blob/master/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProviderFactory.java

```
mapperModel = KeycloakModelUtils.createComponentModel("username", model.getId(), UserAttributeLDAPStorageMapperFactory.PROVIDER_ID, LDAPStorageMapper.class.getName(),
                UserAttributeLDAPStorageMapper.USER_MODEL_ATTRIBUTE, UserModel.USERNAME,
                UserAttributeLDAPStorageMapper.LDAP_ATTRIBUTE, usernameLdapAttribute,
                UserAttributeLDAPStorageMapper.READ_ONLY, readOnly,
                UserAttributeLDAPStorageMapper.ALWAYS_READ_VALUE_FROM_LDAP, "false",
                UserAttributeLDAPStorageMapper.IS_MANDATORY_IN_LDAP, "true");
        realm.addComponentModel(mapperModel);

```

But maybe it is too much work. At least, we should better document how to create the mappers based on what France Connect provides.
