### ISSUE TITLE
[FEAT] Pro Connect

### ISSUE THREAD

**Issue by garronej** [InseeFr/Keycloak-FranceConnect#120]
Hello,  

Thank you very much for this package!  

AgentConnect have been merged into ProConnect?  
Any plan to support ProConnect? What would be the required changes?  

Thanks in advance.  

PS: We are overhauling https://github.com/codegouvfr/keycloak-theme-dsfr

**Comment by clement-dufaure** [comment]
Hello,

Technically, ProConnect is a rebranding of the same technical solution as AgentConnect, including the same URL, which remains "auth.agentconnect.gouv.fr" for now (https://github.com/numerique-gouv/proconnect-documentation/blob/main/resources/valeur_ac_domain.md).

Support is already included by choosing AgentConnect, but the existing documentation and the button design in the default theme would need to be updated. (However, I’m not sure if the default theme provided is actually used...)

We could also change the provider’s name, but doing so might compromise backward compatibility. I believe it’s better to wait for a potential change in the AgentConnect/ProConnect URL before considering modifications to the provider name.
(We could potentially duplicate the entire AgentConnect feature with a new ID "proconnect", but...)

About your theme, you can just change line https://github.com/codegouvfr/keycloak-theme-dsfr/blob/612062bd08de8a5fa01a5229a64aeb7fab27e31c/src/login/pages/Login.tsx#L57 by the same content of line https://github.com/codegouvfr/keycloak-theme-dsfr/blob/612062bd08de8a5fa01a5229a64aeb7fab27e31c/src/login/pages/Login.tsx#L61 (so remove proconnect case or make a "or " statement to prepare a future rebranding of the provider as "proconnect")

**Comment by garronej** [comment]
Ok that makes a lot of sense, thak you!
