### ISSUE TITLE
[HELP/FEAT] Support France Connect + (was: France connect compatibility : API v1 vs v2, update URL ? )

### ISSUE THREAD

**Issue by semangard** [InseeFr/Keycloak-FranceConnect#52]
Hello,

--- [HELP] --- 
As you can see on the diagram below the URL used by the KeyCloak extension seems to be DEPRECATED
![image](https://user-images.githubusercontent.com/57065741/135804678-b5b871fb-1951-4af5-ba91-89af44940ddc.png)

Do you plan to release a version with the right URL ?

France Connect official doc : https://github.com/france-connect/Documentation-FranceConnect-Plus/blob/main/fs/docs-fs.md

--- [FEAT] --- 
Would it be possible to let admin modify the root URL of the API and thus maybe make you provider compliant with latest version of France Connect API ?

Regards

**Comment by semangard** [comment]
Please double-check URL used by AgentConnect Protocol ... because I am not sure it is the same as FranceConnect V2

**Comment by semangard** [comment]
I have a _client_id_ and _client_secret_ to realize some tests with FranceConnect V2 yes (but I cannot share these creds with you :-))

**Comment by micedre** [comment]
I'm not asking for it :) Ok I'll try to publish some things soon.

**Comment by micedre** [comment]
Could you try with this jar : https://github.com/InseeFr/Keycloak-FranceConnect/releases/download/3.0-beta-fcv2/keycloak-franceconnect-3.0-beta-fcv2.jar ?

**Comment by semangard** [comment]
Tested:
Always an issue ... due to the nonce length ?
![image](https://user-images.githubusercontent.com/57065741/136240577-cf504468-4c7a-4ae1-bc1a-7d11e67f24ed.png)

**Comment by micedre** [comment]
here https://github.com/InseeFr/Keycloak-FranceConnect/releases/download/3.0-beta2-fcv2/keycloak-franceconnect-3.0-beta2-fcv2.jar

Sorry I didn"t understand a fixed size was required. I don't like to go against the specs, but it's not the first time for france connect. Please tell me if it works better.

**Comment by semangard** [comment]
OK I will test
please not also that I got this into the logs:
![image](https://user-images.githubusercontent.com/57065741/136259837-c58cf5ac-9c8f-4d7a-94e4-7cc11181ce25.png)

**Comment by semangard** [comment]
Test result : always an error Y030007 even with a longer nonce => sent to FC for analysis 

nonce=wdKBAy2xRTamjg6yXkZ0Gw,48ZEoFN5JAKJUaBsPVbiubjK_YjNr6hzyCws6N7k7wYrUyq5RoO-1xQJyiEH6EPc

a) I do not know if ',' is allowed...
b) Length might be too long now....because _"le nonce doit faire **exactement** 64 caractères "_

![image](https://user-images.githubusercontent.com/57065741/136260610-488b867e-ab22-47bc-b020-c364f3f627e7.png)

**Comment by micedre** [comment]
ok, my bad, here this should be exactly 64 Bytes : https://github.com/InseeFr/Keycloak-FranceConnect/releases/download/3.0-beta3-fcv2/keycloak-franceconnect-3.0-beta3-fcv2.jar

**Comment by semangard** [comment]
I tested with Edge that last time (and not Edge) => URL correctly encoded (Firefox just diplays it decoded)
=> Issue sent back to FC
![image](https://user-images.githubusercontent.com/57065741/136364277-d0a0fd43-e5ba-4f87-b444-5cba02fe0222.png)

**Comment by semangard** [comment]
According to me yes, but I asked my network team to double-check

**Comment by micedre** [comment]
I finally had some way to test the service, and a working implementation (at least for me) is here : 
https://minio.lab.sspcloud.fr/projet-keycloak-franceconnect/keycloak-franceconnect-2.4-SNAPSHOT.jar

Configuration is done like this : 
![image](https://user-images.githubusercontent.com/243027/140404107-7a86375c-901e-489d-92e5-86a1b152775c.png)

Could you test it, and see if it works for you (I did add a lot of logs so it is a bit verbose)

**Comment by micedre** [comment]
You will also need to add a key to jwks uri, you can do it like explained here : https://github.com/InseeFr/Keycloak-FranceConnect/discussions/58#discussioncomment-1575900

**Comment by micedre** [comment]
And lastly, this only supports keycloak version > 15

**Comment by semangard** [comment]
Thanks for your feedback.

- Can you tell us why it is only supported by KC > 15 ? (or event>=15 ?)
- Do you know if KC plan to deliver something more relevant to manage the trick of  #58 ?

**Comment by micedre** [comment]
* Keycloak added support for publishing enc keys to jwks only since keycloak 15.0.0 (otherwise only "sig" keys are published). There may be a way to work around it, by generating the rsa key manually, importing it in keycloak, and publish the jwks elsewhere for France Connect, I didn't test it at the moment. That said, it is always a good idea to upgrade keycloak version :)
* for adding the key, I 'll try to add something in the extension soon, and there is an issue in keycloak bug tracker on this but no fix yet.

**Comment by remigauthierdocaposte** [comment]
Just to let you know @micedre, the last version you shared works on our side. Thanks again for the work! We are indeed using v15.0.2

**Comment by micedre** [comment]
> Just to let you know @micedre, the last version you shared works on our side. Thanks again for the work! We are indeed using v15.0.2

Great, thank you both for your inputs. I will release a clean version soon.

**Comment by semangard** [comment]
Does _keycloak-franceconnect-2.4-SNAPSHOT.jar_  take into account all what was released into _keycloak-franceconnect-3.0-beta4-fcv2.jar_ ?

**Comment by micedre** [comment]
Yes it should

**Comment by micedre** [comment]
I just released the 4.0.0 version which should work with FC+ (there is some docs in wiki). @semangard there is a new key provider to generate the key needed for FC+ directly from the admin console.

https://github.com/InseeFr/Keycloak-FranceConnect/releases/tag/4.0.0

**Comment by semangard** [comment]
@micedre : thanks, we will test ... not immediatly unfortunately because we need to upgrade our KC instances...
