### ISSUE TITLE
[HELP/FEAT] France connect V2 : nonce's lenght constraint  ? 

### ISSUE THREAD

**Issue by semangard** [InseeFr/Keycloak-FranceConnect#53]
Hello,

As indicated into https://github.com/InseeFr/Keycloak-FranceConnect/issues/52
we would like to use your KC extension with FranceConnect V2 but we are facing issues with target URL.

Meanwhile, we tried to configure and use a default KC OIDC provider.
But we are facing some HTTP error code from France Connect V2 because the acr is missing and also because the nonce does not have the expected length.

According to : 
https://github.com/InseeFr/Keycloak-FranceConnect/blob/master/src/main/java/fr/insee/keycloak/provider/FranceConnectIdentityProvider.java
we see that indeed you added the acr
but what about the nonce ? 
Have you also faced issues with the nonce's lenght and customized something into your extension ?

Regards

**Comment by micedre** [comment]
The extension doesn't do anything on the nonce. Which keycloak version are you using?

**Comment by semangard** [comment]
KeyCloak version 11

**Comment by semangard** [comment]
![image](https://user-images.githubusercontent.com/57065741/136204721-59f2269a-7ee9-4f14-9be6-4f5fafab7c84.png)

**Comment by micedre** [comment]
I never had that error, could you try asking france connect team about it ? There shouldn't be a size limit on nonce.

**Comment by semangard** [comment]
I asked and the answer is exactly : _"le nonce doit faire exactement 64 caractères"_

**Comment by semangard** [comment]
it was the answer of FC

**Comment by semangard** [comment]
Sent to your pro email.

**Comment by micedre** [comment]
Also, the nonce should not contain underscore. A fix for that in the new release here : https://github.com/InseeFr/Keycloak-FranceConnect/releases/download/3.0-beta4-fcv2/keycloak-franceconnect-3.0-beta4-fcv2.jar

**Comment by micedre** [comment]
Released here : https://github.com/InseeFr/Keycloak-FranceConnect/releases/tag/4.0.0
