### ISSUE TITLE
[BUG] Manage logout for FranceConnect+

### ISSUE THREAD

**Issue by micedre** [InseeFr/Keycloak-FranceConnect#60]
At the moment logout is not working for the FranceConnect+ provider. This should be implemented following the spec as explained here : 
https://github.com/france-connect/Documentation-FranceConnect-Plus/blob/main/fs/docs-fs.md#cin%C3%A9matique-de-d%C3%A9connexion-par-un-fournisseur-de-service

**Comment by remigauthierdocaposte** [comment]
BUG is reproduced on my side too, no workaround found. A ticket is about to be created to FC support about this. We at least need to get the documentation reflecting the actual implemented behavior.

**Comment by micedre** [comment]
Please share France Connect response on this. I didn't manage to make it working yet.

**Comment by remigauthierdocaposte** [comment]
Ticket will be opened today, I ll let you know.

**Comment by remigauthierdocaposte** [comment]
FYI the correct url is not `/logout`, it is `/session/end` (for integration it is `https://auth.integ01.dev-franceconnect.fr/api/v2/session/end`). The FranceConnect documentation should be updated to reflect this is the next days. Also be aware that the redirect uri post logout needs to be authorized by FranceConnect. I'll try today to test this (hopefully).

**Comment by micedre** [comment]
Thanks, the redirect_uri to ask for is https://<keycloak-url>/auth/realms/<realm>/broker/franceconnect-particulier/endpoint/logout_response

I'll change the uri used in the extension asap.

**Comment by micedre** [comment]
FranceConnect and AgentConnect source here https://github.com/france-connect/sources 

This will help implementation :)

**Comment by micedre** [comment]
https://minio.lab.sspcloud.fr/projet-keycloak-franceconnect/keycloak-franceconnect-4.0.0-SNAPSHOT.jar here for a jar which fix logout url for FC+. 

It is installed here https://keycloak.dev.insee.io/auth/realms/test-fc/account but there is still an error.

**Comment by micedre** [comment]
@remigauthierdocaposte a working version is here: https://minio.lab.sspcloud.fr/projet-keycloak-franceconnect/keycloak-franceconnect-4.0.0-SNAPSHOT.jar 

FC + needs the id_token decrypted for logout, which seems weird. I'm waiting for an answer on this, and then I'll release a new version.

**Comment by remigauthierdocaposte** [comment]
Yes indeed, the IdToken decrypted is needed in the current FC+ deployed version for logout. Sorry for not following up on this. It is not usable as is since we are sending sensitive information. Not sure if FC+ will support minimalist IdToken or encrypted one. We are waiting for FC+ response on this point.

**Comment by remigauthierdocaposte** [comment]
I just tested your version it is working. Still no news from FC+ on this specific point.
