### ISSUE TITLE
[HELP] Ensure FC plugin is compatible with Keycloak 17

### ISSUE THREAD

**Issue by mboisnard** [InseeFr/Keycloak-FranceConnect#70]
Can you check that FC plugin works with Keycloak 17 which uses Quarkus instead of Wildfly?

**Comment by micedre** [comment]
I just tested with quarkus distribution on FranceConnect V1, it works fine. I'll test the others providers as soon as possible.

**Comment by semangard** [comment]
hello @micedre 
would it be possible to share your configuration for KC 17 (especially where you deploy your jar) ?

**Comment by micedre** [comment]
With keycloak 17 the docker image is based on the quarkus distribution, I thibk you need to place extensions in KEYCLOAK_HOME/providers. In your case you should replace /opt/keycloak/standalone/deployments with /opt/keycloak/providers

**Comment by semangard** [comment]
OK @micedre 
It is better now 👍 
![image](https://user-images.githubusercontent.com/57065741/159565016-549c3c9a-f570-4d9d-a317-8ab147ff86ef.png)
