### ISSUE TITLE
[BUG] Unable to select the FranceConnect environment with the new Keycloak admin console

### ISSUE THREAD

**Issue by lme-atolcd** [InseeFr/Keycloak-FranceConnect#74]
**Describe the bug**
With the new default Keycloak admin console available since version 19 (Admin console theme `keycloak.v2`), it's not possible to select the FranceConnect environment when adding a new Identity provider of type "Franceconnect-particulier". It seems the extension is missing ressources for the new theme.
It's possible to switch to the old theme (Admin console theme `keycloak`) then the FranceConnect environment field is available when adding a new Identity provider of type "Franceconnect-particulier"

**To Reproduce**
1. install Keycloak 19 and the FranceConnect extension version 4.1.0
2. go to Keycloak admin console
3. create a new realm
4. go to that realm
5. go to "Configure > Identity providers"
6. select "Social > France Connect Particulier"
7. the FranceConnect environment field is not available

**Expected behavior**

The FranceConnect environment field is displayed in the identity provider settings page. 

**Screenshots**
![Screenshot 2022-10-20 at 09-35-15 Keycloak Administration Console](https://user-images.githubusercontent.com/116001482/196885999-991ab6c1-8716-47f5-a4dd-755c8580c8c4.png)

**Additional context**
 - Keycloak Version 19.0.3
 - Browser Firefox/Chrome
 - Version 4.1.0

**Comment by mboisnard** [comment]
@lme-atolcd at the moment, there is no way to add custom properties (EIDAS level) to the new Identity Providers page.
This feature will be added to Keycloak 21 with the removal of the old interface. (see https://github.com/keycloak/keycloak/issues/15344)

**Comment by clement-dufaure** [comment]
to avoid waiting custom attribute integration, a solution could be to split into 3 providers, one for each eidas level
the other attributes could became standard : integration/production => manual url declaration
except ignoreAbsentStateParameterLogout, don't know if it has to persist

**Comment by clement-dufaure** [comment]
So unique configuration for whole keycloak instance ?

**Comment by remigauthierdocaposte** [comment]
Hello, any update on this topic? The behavior allowing to choose the env (int / prod) or the type (V1 for FC / V2 for FC+) was OK. Do you plan to correct this part soon? Can we do it and propose it to you?

**Comment by remigauthierdocaposte** [comment]
Just saw this https://github.com/keycloak/keycloak/issues/15344 ...

**Comment by clement-dufaure** [comment]
Sorry, we are restarting works on this issue.
I think if you have sql elements, you can share it here, it can be useful for other users.

Definitly, i think long term solution is to provide a more standard provider without helpers on urls (no longer selection of "integration" and "production"), and to split into 3 providers for each eidas level required

**Comment by clement-dufaure** [comment]
WIP but a draft of spliting into providers for each eidas level : https://github.com/InseeFr/Keycloak-FranceConnect/pull/87

just don't know what to do about custom parameter ignoreAbsentStateParameterLogout if it's still useful

**Comment by remigauthierdocaposte** [comment]
**To retrieve all configurations related to FranceConnect:**

```sql
SELECT r.NAME as realm_name, ip.PROVIDER_ALIAS, ip.PROVIDER_ID, ipc.VALUE, ipc.NAME, ipc.IDENTITY_PROVIDER_ID
FROM IDENTITY_PROVIDER_CONFIG ipc
LEFT JOIN IDENTITY_PROVIDER ip ON ip.INTERNAL_ID  = ipc.IDENTITY_PROVIDER_ID 
LEFT JOIN REALM r ON r.ID = ip.REALM_ID 
WHERE ip.provider_id = 'franceconnect-particulier';
```

**To insert the necessary configurations for FranceConnect:**

* Change the realm name in `r.NAME = 'NOM_DU_ROYAUME'`

```sql
INSERT INTO IDENTITY_PROVIDER_CONFIG (IDENTITY_PROVIDER_ID, VALUE, NAME)
SELECT unique ipc.IDENTITY_PROVIDER_ID, "integration_v1", "fc_environment"
FROM IDENTITY_PROVIDER_CONFIG ipc
LEFT JOIN IDENTITY_PROVIDER ip ON ip.INTERNAL_ID  = ipc.IDENTITY_PROVIDER_ID 
LEFT JOIN REALM r ON r.ID = ip.REALM_ID 
WHERE ip.provider_id = 'franceconnect-particulier'
AND r.NAME = 'NOM_DU_ROYAUME';

INSERT INTO IDENTITY_PROVIDER_CONFIG (IDENTITY_PROVIDER_ID, VALUE, NAME)
SELECT unique ipc.IDENTITY_PROVIDER_ID, "eidas2", "eidas_values"
FROM IDENTITY_PROVIDER_CONFIG ipc
LEFT JOIN IDENTITY_PROVIDER ip ON ip.INTERNAL_ID  = ipc.IDENTITY_PROVIDER_ID 
LEFT JOIN REALM r ON r.ID = ip.REALM_ID 
WHERE ip.provider_id = 'franceconnect-particulier'
AND r.NAME = 'NOM_DU_ROYAUME';
```

**To update existing configurations for the `fc_environment` value :**

* Change `ipc.VALUE='integration_v2'` with the desired value :
  - integration_v1
  - integration_v2
  - production_v1
  - production_v2

* Also, change the realm name in `r.NAME = 'NOM_DU_ROYAUME'`

```sql
UPDATE IDENTITY_PROVIDER_CONFIG ipc
SET ipc.VALUE='integration_v2'
WHERE ipc.NAME='fc_environment'
AND ipc.IDENTITY_PROVIDER_ID IN (
    SELECT ipc_check.IDENTITY_PROVIDER_ID
    FROM IDENTITY_PROVIDER_CONFIG ipc_check
    LEFT JOIN IDENTITY_PROVIDER ip ON ip.INTERNAL_ID  = ipc.IDENTITY_PROVIDER_ID 
	LEFT JOIN REALM r ON r.ID = ip.REALM_ID 
    WHERE ipc_check.NAME='fc_environment' 
    AND r.NAME = 'NOM_DU_ROYAUME'
);
```

**To update existing configurations for the `eidas_values`:**

* Change `ipc.VALUE='eidas1'` with the desired value :
  - eidas1
  - eidas2
  - eidas3

* Also, change the realm name in `r.NAME = 'NOM_DU_ROYAUME'`

```sql
UPDATE IDENTITY_PROVIDER_CONFIG ipc
SET ipc.VALUE='eidas2'
WHERE ipc.NAME='eidas_values'
AND ipc.IDENTITY_PROVIDER_ID IN (
    SELECT ipc_check.IDENTITY_PROVIDER_ID
    FROM IDENTITY_PROVIDER_CONFIG ipc_check
    LEFT JOIN IDENTITY_PROVIDER ip ON ip.INTERNAL_ID  = ipc.IDENTITY_PROVIDER_ID 
	LEFT JOIN REALM r ON r.ID = ip.REALM_ID 
    WHERE ipc_check.NAME='eidas_values' 
    AND r.NAME = 'NOM_DU_ROYAUME'
);
```

**Comment by clement-dufaure** [comment]
Sorry, no more news about configuring it in keycloak admin view, Just a complement of previous comment.
For AgentConnect configurations, when setting environment by sql :
- Change `ipc.VALUE='integration_v2'` with the desired value :
   - integration_rie
   - integration_internet
   - production_rie
   - production_internet
