### ISSUE TITLE
[BUG] Plugin not compatible with Keycloak 22

### ISSUE THREAD

**Issue by bardyguillaume** [InseeFr/Keycloak-FranceConnect#96]
**Describe the bug**
Plugin not compatible with Keycloak 22

**To Reproduce**
1. Install plugin last version (5.0.0) (providers folder) within a Keycloak 22
2. Try to use the plugin (you have class not found error linked to javax -> jakarta)

**Expected behavior**
A release is needed for keycloak core breaking changes (jdk 17 , jakarta, etc.)

**Screenshots**
Not applicable 

**Additional context**
 - Keycloak Version 22
 - All Browser 
 - Version 22

**Comment by bardyguillaume** [comment]
#95 allows to resolve this issue with keycloak 22. (new release needed)

**Comment by clement-dufaure** [comment]
release 6.0.0
