### ISSUE TITLE
[BUG] Admin fc-ac-theme pollutes logs

### ISSUE THREAD

**Issue by olivierdepriester** [InseeFr/Keycloak-FranceConnect#99]
**Describe the bug**
When saving themes of a realm, the logs are polluted with warn and error messages due to the misconfiguration of `fc-ac-theme`. As this theme extends `keycloak` theme, it triggers the error because `keycloak` theme has no admin theme anymore. Maybe it would be better to remove the `fc-ac-theme` admin theme until there is a way to "extend" from the `keycloak.v2` admin theme (I am not even sure this will happen)

**To Reproduce**
1. Go to 'Realm Settings' > 'Themes'
2. Click on 'Save' button
3. See logs: 
```log
[exec] 2023-09-29 17:59:04,880 WARN  [executor-thread] org.keycloak.theme.DefaultThemeManager             : Not found parent theme 'keycloak' of theme 'fc-ac-theme'. Unable to load ADMIN theme 'fc-ac-theme' due to this.
[exec] 2023-09-29 17:59:04,880 ERROR [executor-thread] org.keycloak.theme.DefaultThemeManager             : Failed to find ADMIN theme fc-ac-theme, using built-in themes
```

**Expected behavior**
No logs should appear

**Additional context**
 - Keycloak Version  : 22.0.3

**Comment by clement-dufaure** [comment]
fixed in #105
